// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVc3vR78IbTS8wPu1et3Wa4vyoXmxw3Mk',
    appId: '1:324650977096:android:b3d19d6470ba12e714557d',
    messagingSenderId: '324650977096',
    projectId: 'flutter-prep-d3128',
    databaseURL: 'https://flutter-prep-d3128-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-prep-d3128.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsS8uPOCJ9Xfqxu7RsP4v87zuvqFhZ9y4',
    appId: '1:324650977096:ios:ca70df531a3cb7a814557d',
    messagingSenderId: '324650977096',
    projectId: 'flutter-prep-d3128',
    databaseURL: 'https://flutter-prep-d3128-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-prep-d3128.firebasestorage.app',
    iosBundleId: 'com.example.bookStore',
  );
}
